# Compiler
CC = gcc

# Compiler flags
CFLAGS = -Wall -Wextra -std=c99

# Target executable name
TARGET = fila_sequencial

# Source files
SRC = main.c fila.c

# Header files
HEADERS = fila.h

# Object files (automatically generated by replacing .c with .o in SRC)
OBJ = $(SRC:.c=.o)

# Default target: Build the executable
all: $(TARGET)

# Rule to build the executable
$(TARGET): $(OBJ)
	$(CC) $(CFLAGS) -o $@ $^

# Rule to build object files
%.o: %.c $(HEADERS)
	$(CC) $(CFLAGS) -c $< -o $@

# Clean the build directory
clean:
	rm -f $(OBJ) $(TARGET)

# Phony targets to prevent conflicts with files of the same name
.PHONY: all clean
